# Generated by Django 6.0.5 on 2026-05-27 16:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('event_type', models.CharField(default='scheduled_charge', max_length=40)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('day_of_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('auto_post', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('receivable', 'Receivable'), ('payable', 'Payable')], max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField(default=4)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['obligation_id', 'account_type'],
            },
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField(default=4)),
                ('opened_on', models.DateField()),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('canceled', 'Canceled')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-opened_on', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EventSeriesVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_units', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField(default=4)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('event_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ledger.eventseries')),
            ],
            options={
                'ordering': ['event_series_id', 'valid_from'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('principal_advance', 'Principal advance'), ('repayment', 'Repayment'), ('scheduled_charge', 'Scheduled charge'), ('interest_posting', 'Interest posting'), ('adjustment', 'Adjustment')], max_length=40)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('generated', 'Generated'), ('system', 'System')], default='manual', max_length=20)),
                ('event_date', models.DateField()),
                ('amount_units', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField(default=4)),
                ('direction', models.CharField(choices=[('increases_debt', 'Increases debt'), ('decreases_debt', 'Decreases debt')], max_length=20)),
                ('memo', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('event_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_events', to='ledger.eventseries')),
                ('event_series_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_events', to='ledger.eventseriesversion')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_events', to='ledger.obligation')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('principal_advance', 'Principal advance'), ('repayment', 'Repayment'), ('scheduled_charge', 'Scheduled charge'), ('interest_posting', 'Interest posting'), ('adjustment', 'Adjustment')], max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('transaction_date', models.DateField()),
                ('idempotency_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('memo', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('financial_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_transaction', to='ledger.financialevent')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_transactions', to='ledger.obligation')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('principal_advance', 'Principal advance'), ('repayment', 'Repayment'), ('scheduled_charge', 'Scheduled charge'), ('interest_posting', 'Interest posting'), ('adjustment', 'Adjustment')], max_length=40)),
                ('effective_date', models.DateField()),
                ('side', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount_units', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('currency_exponent', models.PositiveSmallIntegerField(default=4)),
                ('memo', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.ledgeraccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ledger.ledgertransaction')),
            ],
            options={
                'ordering': ['effective_date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='obligation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='ledger.obligation'),
        ),
        migrations.CreateModel(
            name='InterestRatePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_rate_percent', models.DecimalField(decimal_places=4, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_rate_periods', to='ledger.obligation')),
            ],
            options={
                'ordering': ['obligation_id', 'effective_from'],
            },
        ),
        migrations.AddField(
            model_name='eventseries',
            name='obligation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_series', to='ledger.obligation'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_audit_events', to=settings.AUTH_USER_MODEL)),
                ('financial_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='ledger.financialevent')),
                ('obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ledger.obligation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.AddField(
            model_name='obligation',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_obligations', to='ledger.person'),
        ),
        migrations.AddField(
            model_name='obligation',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_obligations', to='ledger.person'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to='ledger.person'),
        ),
        migrations.CreateModel(
            name='InterestAccrualRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('posted_on', models.DateField()),
                ('calculated_interest_amount_units', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('posted', 'Posted'), ('voided', 'Voided')], default='calculated', max_length=20)),
                ('calculation_payload', models.JSONField(blank=True, default=dict)),
                ('ledger_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interest_accrual_run', to='ledger.ledgertransaction')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_accrual_runs', to='ledger.obligation')),
            ],
            options={
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('obligation', 'period_start', 'period_end'), name='unique_interest_run_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='financialevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_series__isnull', False), ('period_start__isnull', False)), fields=('event_series', 'period_start'), name='unique_series_period_event'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('obligation', 'account_type'), name='unique_obligation_account_type'),
        ),
    ]
