# Generated by Django 6.0.5 on 2026-05-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_use_auth_users_directly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interestaccrualrun',
            options={'ordering': ['-period_start', '-revision']},
        ),
        migrations.RemoveConstraint(
            model_name='interestaccrualrun',
            name='unique_interest_run_period',
        ),
        migrations.AddField(
            model_name='interestaccrualrun',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='interestaccrualrun',
            constraint=models.UniqueConstraint(fields=('obligation', 'period_start', 'period_end', 'revision'), name='unique_interest_run_period_revision'),
        ),
        migrations.AddConstraint(
            model_name='interestaccrualrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'posted')), fields=('obligation', 'period_start', 'period_end'), name='unique_posted_interest_run_period'),
        ),
    ]
