# Generated by Django 6.0.5 on 2026-05-27 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_interest_run_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseries',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Every 2 weeks'), ('weekly', 'Weekly')], default='monthly', max_length=20),
        ),
    ]
