# Generated by Django 6.0.5 on 2026-05-28 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_recurring_weekly_biweekly'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='financialevent',
            name='unique_series_period_event',
        ),
        migrations.AddField(
            model_name='financialevent',
            name='revision',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='financialevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_series__isnull', False), ('period_start__isnull', False)), fields=('event_series', 'period_start', 'revision'), name='unique_series_period_event_revision'),
        ),
        migrations.AddConstraint(
            model_name='financialevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_series__isnull', False), ('period_start__isnull', False), ('voided_at__isnull', True)), fields=('event_series', 'period_start'), name='unique_active_series_period_event'),
        ),
    ]
