# Generated by Codex on 2026-05-28

import django.db.models.deletion
from django.db import migrations, models


def migrate_obligation_categories(apps, schema_editor):
    obligation_model = apps.get_model('ledger', 'Obligation')
    category_model = apps.get_model('ledger', 'ObligationCategory')

    for obligation in obligation_model.objects.exclude(legacy_category=''):
        category_name = obligation.legacy_category.strip()
        if not category_name:
            continue
        category, _ = category_model.objects.get_or_create(name=category_name)
        obligation.category = category
        obligation.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_remove_financialevent_unique_series_period_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'obligation categories',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='obligation',
            old_name='category',
            new_name='legacy_category',
        ),
        migrations.AddField(
            model_name='obligation',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='obligations',
                to='ledger.obligationcategory',
            ),
        ),
        migrations.RunPython(migrate_obligation_categories, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='obligation',
            name='legacy_category',
        ),
    ]
