# Generated by Django 6.0.5 on 2026-06-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_user_profile_telegram_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_dashboard_balance_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_planner_module',
            field=models.BooleanField(default=True),
        ),
    ]
